name: Pull Request validation and linting

on: [pull_request]

jobs:
  build:
    name: Linting
    runs-on: ubuntu-latest

    steps:
      - name: EditorConfig
        uses: zbeekman/EditorConfig-Action@v1.1.1

